es_name: "CRFMNES"
problem_type: "waterworld_ma"
normalize: false
es_config:
  pop_size: 16
  init_stdev: 0.09
hidden_size: 100
num_tests: 16
n_repeats: 64
max_iter: 2000
test_interval: 100
log_interval: 10
seed: 97
gpu_id: [0, 1, 2, 3]
debug: false
